module.exports = {
  margin: ['responsive', 'hover', 'first', 'last', 'group-hover'],
  padding: ['responsive', 'hover', 'first', 'last'],
  width: ['group-hover', 'group-focus'],
  transitionProperty: ['responsive'],
  transformOrigin: ['hover', 'focus'],
  fontWeight: ['focus', 'hover'],
  fontSize: ['focus', 'hover', 'group-hover', 'group-focus', 'sibling-focus'],
  translate: ['active', 'group-hover', 'sibling-focus'],
  display: ['group-hover'],
  transform: ['hover', 'group-hover'],
  zIndex: ['hover', 'active', 'group-hover'],
  borderWidth: ['hover', 'focus', 'focus-within'],
  inset: ['hover', 'focus', 'group-hover', 'group-focus', 'sibling-focus'],
  backgroundColor: ['active'],
  animation: ['responsive', 'motion-safe', 'motion-reduce'],
};
